#-----------------------------------------------------------------------
APP         :=TestCalcApp
TARGET      :=TestCalcClient
CONFIG      :=
STRIP_FLAG  := N

INCLUDE     += -I/home/tarsproto/TestCalcApp/CalcServer/
LIB         +=
#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------